@extends('layouts.app')
@section('content')
<div class="finance-page" dir="rtl">
  <div class="finance-head"><div><span class="eyebrow">پرداخت امن فراست</span><h1>تأیید و پرداخت سفارش</h1><p>قیمت پیش از پرداخت دوباره از متن نهایی محاسبه می‌شود؛ تغییرات بعد از پرداخت نیازمند سفارش جدید است.</p></div><a class="finance-back" href="/wallet"><i class="fa-solid fa-wallet"></i> کیف پول</a></div>
  @if($errors->any())<div class="finance-alert danger"><i class="fa-solid fa-circle-exclamation"></i>{{ $errors->first() }}</div>@endif
  <div class="checkout-grid">
    <section class="checkout-card"><div class="card-title"><span><i class="fa-solid fa-receipt"></i></span><div><h2>خلاصه سفارش</h2><small>سفارش شماره {{ $order->id }}</small></div></div><div class="invoice-lines"><div><span>هزینه خدمات</span><b>{{ number_format($order->subtotal_rials) }} ریال</b></div><div><span>هدیه رایگان</span><b class="discount">{{ number_format($order->discount_rials) }}- ریال</b></div><div><span>مالیات و عوارض</span><b>{{ number_format($order->tax_rials) }} ریال</b></div><div class="total"><span>مبلغ قابل پرداخت</span><strong>{{ number_format($order->total_rials) }} ریال</strong></div></div><div class="legal-box"><i class="fa-solid fa-shield-halved"></i><p>با پرداخت، تأیید می‌کنید که متن را پیش از پرداخت بررسی کرده‌اید و مبلغ بر مبنای نسخه نهایی محاسبه شده است. تغییر محتوای سند پس از پرداخت، خروجی همان سفارش را نامعتبر می‌کند.</p></div></section>
    <section class="checkout-card pay-card"><div class="card-title"><span><i class="fa-solid fa-credit-card"></i></span><div><h2>روش پرداخت</h2><small>پرداخت از موجودی کیف پول</small></div></div><div class="wallet-balance"><span>موجودی فعلی</span><strong>{{ number_format($wallet->balance_rials) }} <small>ریال</small></strong></div><form method="post" action="{{ route('checkout.wallet',$order) }}">@csrf<label class="terms-check"><input type="checkbox" name="accept_terms" value="1" required><span>قوانین پرداخت، قیمت‌گذاری و شرایط استفاده را مطالعه کرده‌ام و می‌پذیرم.</span></label><button class="pay-button" type="submit" {{ $wallet->balance_rials < $order->total_rials ? 'disabled' : '' }}><i class="fa-solid fa-lock"></i> پرداخت {{ number_format($order->total_rials) }} ریال</button></form>@if($wallet->balance_rials < $order->total_rials)<div class="insufficient"><i class="fa-solid fa-circle-info"></i><span>موجودی کافی نیست. درگاه بانکی باید با اطلاعات پذیرنده واقعی در محیط تولید تنظیم شود.</span></div>@endif<div class="payment-security"><span><i class="fa-solid fa-lock"></i> اتصال امن</span><span><i class="fa-solid fa-file-invoice"></i> فاکتور قابل پیگیری</span><span><i class="fa-solid fa-scale-balanced"></i> محاسبه شفاف</span></div></section>
  </div>
</div>
@endsection
