@extends('layouts.app')
@section('content')
<div class="container user-dashboard" dir="rtl">
  <div class="page-head"><div><span class="eyebrow"><i class="fa-solid fa-gauge-high"></i> فضای کاری</span><h1>داشبورد شما</h1><p class="dashboard-sub">امکانات این پنل توسط مدیر اصلی قابل کنترل است.</p></div><a class="btn primary" href="/editor"><i class="fa-solid fa-plus"></i> تایپ جدید</a></div>
  <div class="cards dashboard-cards"><div><b>{{ $documents->count() }}</b><span><i class="fa-solid fa-file-lines"></i> سندهای اخیر</span></div><div><b>{{ $capabilities['unlimited'] ? '∞' : $capabilities['weekly_free_pages'] }}</b><span><i class="fa-solid fa-gift"></i> صفحه رایگان هفتگی</span></div><div><b>{{ $capabilities['unlimited'] ? 'نامحدود' : $capabilities['daily_ai_requests'] }}</b><span><i class="fa-solid fa-wand-magic-sparkles"></i> AI در روز</span></div><div><b>{{ $capabilities['unlimited'] ? 'نامحدود' : $capabilities['max_file_mb'].' MB' }}</b><span><i class="fa-solid fa-file-arrow-up"></i> سقف فایل</span></div></div>
  <section class="panel capability-panel"><div class="panel-heading"><div><h2>امکانات حساب</h2><p>وضعیت فعلی دسترسی‌های شما</p></div></div><div class="capability-chips">@foreach(['can_type'=>'تایپ و ویرایش','can_ai'=>'هوش مصنوعی','can_voice'=>'تایپ صوتی','can_export_docx'=>'خروجی Word','can_export_pdf'=>'خروجی PDF','can_feedback'=>'بازخورد','can_support'=>'پشتیبانی'] as $key=>$label)<span class="cap-chip {{ $capabilities[$key]?'on':'off' }}"><i class="fa-solid {{ $capabilities[$key]?'fa-check':'fa-lock' }}"></i>{{ $label }}</span>@endforeach</div></section>
  <section class="panel"><div class="panel-heading"><div><h2>سندهای اخیر</h2><p>فایل‌ها به صورت موقت و خصوصی نگه‌داری می‌شوند.</p></div></div>@forelse($documents as $d)<div class="doc"><span><i class="fa-regular fa-file-lines"></i> {{ $d->title }}</span><span>{{ $d->page_count }} صفحه</span><span>{{ number_format($d->price_rials) }} ریال</span><a href="/editor"><i class="fa-solid fa-arrow-left"></i> باز کردن</a></div>@empty<p>هنوز سندی ندارید.</p>@endforelse</section>
</div>
@endsection
