@extends('layouts.app')
@section('content')
<div class="word-app" id="farastWord" dir="rtl" data-authenticated="{{ auth()->check() ? '1' : '0' }}">
  <header class="word-titlebar">
    <div class="word-brand"><span class="word-mark">F</span><div><strong>فراست</strong><small>ویرایشگر هوشمند تایپ</small></div></div>
    <div class="doc-title"><input id="docTitle" value="سند جدید" aria-label="عنوان سند"><span id="saveState">ذخیره نشده</span></div>
    <div class="title-actions"><button type="button" id="saveNow" class="title-btn">ذخیره</button><a href="/dashboard" class="title-btn">بازگشت</a></div>
  </header>
  <nav class="word-tabs" aria-label="نوار ابزار"><button class="word-tab active" data-tab="home">خانه</button><button class="word-tab" data-tab="insert">درج</button><button class="word-tab" data-tab="layout">طرح</button><button class="word-tab" data-tab="review">بازبینی</button><button class="word-tab ai-tab" data-tab="ai">هوش مصنوعی</button></nav>
  <section class="ribbon" id="ribbon-home">
    <div class="ribbon-group history"><button data-cmd="undo" title="واگرد">↶</button><button data-cmd="redo" title="انجام دوباره">↷</button></div>
    <div class="ribbon-group clipboard"><button id="pasteText">چسباندن</button><button data-cmd="removeFormat">پاک‌کردن قالب</button></div>
    <div class="ribbon-group font-group"><select id="fontName"><option value="B Nazanin">B Nazanin</option><option value="B Titr">B Titr</option><option value="B Mitra">B Mitra</option><option value="Tahoma">Tahoma</option><option value="Arial">Arial</option></select><select id="fontSize"><option value="16" selected>16</option><option value="12">12</option><option value="14">14</option><option value="18">18</option><option value="20">20</option><option value="24">24</option><option value="28">28</option><option value="32">32</option></select><button data-cmd="bold"><b>ن</b></button><button data-cmd="italic"><i>ک</i></button><button data-cmd="underline"><u>ز</u></button><button data-cmd="strikeThrough">abc</button></div>
    <div class="ribbon-group paragraph-group"><button data-cmd="justifyRight">≡→</button><button data-cmd="justifyCenter">≡↔</button><button data-cmd="justifyLeft">←≡</button><button data-cmd="insertUnorderedList">•☰</button><button data-cmd="insertOrderedList">1☰</button><button id="lineSpacing">↕</button></div>
    <div class="ribbon-group style-group"><button data-style="p">متن عادی</button><button data-style="h1">عنوان ۱</button><button data-style="h2">عنوان ۲</button><button data-style="blockquote">نقل‌قول</button></div>
    <div class="ribbon-group tools-group"><button id="findText">یافتن</button><button id="replaceText">جایگزینی</button><button id="mic">🎙 صوت</button><label class="ribbon-file">باز کردن فایل<input id="source" type="file" accept="image/*,.pdf,.zip"></label><button id="analyze" class="ai-run" disabled>تایپ با AI</button></div>
  </section>
  <section class="ribbon ribbon-secondary hidden" id="ribbon-insert"><div class="ribbon-group"><button data-cmd="insertHorizontalRule">خط افقی</button><button id="pageBreak">صفحه جدید</button><button id="insertDate">تاریخ</button></div><div class="ribbon-group"><button id="insertLink">پیوند</button><button id="clearLink">حذف پیوند</button></div></section>
  <section class="ribbon ribbon-secondary hidden" id="ribbon-layout"><div class="ribbon-group"><label>حاشیه <select id="margin"><option value="normal">عادی</option><option value="narrow">کم</option><option value="wide">زیاد</option></select></label><label>اندازه صفحه <select id="paperSize"><option>A4 selected>A4</option><option>A5>A5</option></select></label><button id="direction">راست به چپ</button></div></section>
  <section class="ribbon ribbon-secondary hidden" id="ribbon-review"><div class="ribbon-group"><button id="aiCorrect">بررسی با AI</button><button id="feedbackBad">این خروجی اشتباه است</button><button id="feedbackGood">خروجی خوب بود</button></div><div class="ribbon-group"><span class="review-hint">هوش مصنوعی متن را خودسرانه اصلاح نمی‌کند؛ اصلاحات کاربر به‌عنوان بازخورد ثبت می‌شوند.</span></div></section>
  <section class="ribbon ribbon-secondary hidden" id="ribbon-ai"><div class="ribbon-group ai-status"><span class="status-dot"></span><b>اتصال Gemini</b><span id="aiStatus">آماده</span></div><div class="ribbon-group"><span>شناسه تعامل:</span><code id="interactionId">—</code><span>درخواست:</span><code id="requestId">—</code></div><div class="ribbon-group"><button id="feedbackPanelBtn">ثبت بازخورد</button></div></section>
  <main class="word-body">
    <aside class="ai-sidebar" id="aiSidebar">
      <div class="side-head"><div><strong>دستیار تایپ</strong><small>Gemini • OCR</small></div><button id="closeAi" type="button">×</button></div>
      <div class="source-card"><div class="source-icon">AI</div><div><b id="sourceName">هنوز فایلی انتخاب نشده</b><small id="sourceMeta">فایل را بکشید و رها کنید یا از «باز کردن فایل» استفاده کنید.</small></div></div>
      <div class="ai-stats"><div><small>صفحه</small><b id="pages">۰</b></div><div><small>کلمه</small><b id="words">۰</b></div><div><small>هزینه</small><b id="price">۰ ریال</b></div></div>
      <div class="ai-notice"><b>تست رایگان</b><p>برای تست، هر هفته یک صفحه رایگان دارید. فایل‌های اصلی فقط بعد از ورود پردازش می‌شوند.</p></div>
      <div id="issues" class="issues"></div>
      <div class="feedback-box"><b>کیفیت خروجی</b><p>اگر بخشی اشتباه بود، همان بخش را اصلاح کن تا به‌عنوان داده بازخورد ذخیره شود.</p><div class="feedback-actions"><button id="rate5">✓ درست</button><button id="rate1">✕ اشتباه</button></div></div>
    </aside>
    <section class="document-area" id="documentArea">
      <div class="document-toolbar"><span>نمایش</span><button id="zoomOut">−</button><span id="zoomValue">100%</span><button id="zoomIn">+</button><span class="divider"></span><button id="showAi">پنل هوش مصنوعی</button><span class="autosave" id="autosave">ذخیره خودکار فعال</span></div>
      <div class="upload-zone" id="dropZone"><div class="upload-zone-icon">↑</div><strong>فایل را اینجا بکشید و رها کنید</strong><span>تصویر، PDF یا ZIP تصاویر — تشخیص فرمت خودکار است</span><button type="button" id="chooseFile">انتخاب فایل</button></div>
      <div class="pages-viewport" id="pagesViewport"><div class="word-page" data-page="1"><div id="editor" class="word-editor" contenteditable="true" spellcheck="false" dir="rtl" lang="fa"><p><br></p></div></div></div>
    </section>
  </main>
  <footer class="word-status"><span id="statusText">آماده</span><span>صفحه <b id="currentPage">۱</b> از <b id="totalPages">۱</b></span><span>کلمات <b id="statusWords">۰</b></span><span>زبان: فارسی</span><button id="exportDocx">Word</button><button id="exportPdf">PDF</button></footer>
</div>
<div class="ai-popover hidden" id="aiPopover"><b>واژه مشکوک</b><div id="aiWord"></div><div id="aiSuggestions"></div><button id="keepWord">نگه‌داشتن واژه فعلی</button></div>
<div class="find-dialog hidden" id="findDialog"><div class="dialog-card"><button class="dialog-close" data-close="findDialog">×</button><h3>یافتن و جایگزینی</h3><label>یافتن<input id="findInput"></label><label>جایگزین با<input id="replaceInput"></label><div><button id="findNext">بعدی</button><button id="replaceOne">جایگزینی</button><button id="replaceAll">جایگزینی همه</button></div></div></div>
@endsection
@push('scripts')
<script>
window.FARAST_EDITOR=true;window.FARAST_AUTHENTICATED={{ auth()->check() ? 'true' : 'false' }};
(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],csrf=$('meta[name=csrf-token]').content,editor=$('#editor'),source=$('#source'),analyze=$('#analyze'),dropZone=$('#dropZone');
let docId=null,interactionId=null,requestId=null,saveTimer=null,zoom=1,uploadedPath=null,uploadedMime=null,uploadedName=null;
const nf=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function setStatus(t,ok=false){$('#statusText').textContent=t;$('#saveState').textContent=ok?'ذخیره شد':t}
function api(url,opts={}){opts.headers={...(opts.headers||{}),'X-CSRF-TOKEN':csrf,'Accept':'application/json'};return fetch(url,opts).then(async r=>{let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.message||'خطا در ارتباط با سرور');return j})}
function cmd(c,v=null){editor.focus();document.execCommand(c,false,v);scheduleSave()}
$$('[data-cmd]').forEach(b=>b.onclick=()=>cmd(b.dataset.cmd));
$('#fontName').onchange=e=>cmd('fontName',e.target.value);$('#fontSize').onchange=e=>cmd('fontSize',e.target.value==='16'?4:Math.max(1,Math.min(7,Math.round(Number(e.target.value)/4))));
$$('[data-style]').forEach(b=>b.onclick=()=>cmd('formatBlock','<'+b.dataset.style+'>'));
$('#lineSpacing').onclick=()=>{editor.style.lineHeight=editor.style.lineHeight==='1.15'?'1.5':'1.15';scheduleSave()};
$('#direction').onclick=()=>{editor.dir=editor.dir==='rtl'?'ltr':'rtl';$('#direction').textContent=editor.dir==='rtl'?'راست به چپ':'چپ به راست';scheduleSave()};
$$('.word-tab').forEach(tab=>tab.onclick=()=>{$$('.word-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$$('.ribbon-secondary').forEach(x=>x.classList.add('hidden'));if(tab.dataset.tab!=='home')$('#ribbon-'+tab.dataset.tab).classList.remove('hidden')});
function setSourceState(name,mime,size){uploadedName=name;uploadedMime=mime;$('#sourceName').textContent=name||'فایل آماده است';$('#sourceMeta').textContent=(size?((size/1048576).toFixed(2)+' MB • '):'')+'آماده پردازش';dropZone.classList.add('has-file');analyze.disabled=false;analyze.textContent=window.FARAST_AUTHENTICATED?'تایپ با AI':'ورود و ادامه تایپ'}
async function uploadFile(file){setStatus('در حال آماده‌سازی فایل…');dropZone.classList.add('busy');let fd=new FormData();fd.append('source',file);try{let up=await fetch('/editor/upload',{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:fd}),j=await up.json();if(!up.ok)throw new Error(j.message||'آپلود ناموفق بود');uploadedPath=j.path;uploadedMime=j.mime;uploadedName=j.name;setSourceState(j.name,j.mime,file.size);setStatus(window.FARAST_AUTHENTICATED?'فایل آماده پردازش است':'فایل نگه‌داری شد؛ برای شروع وارد شوید',true)}catch(e){setStatus(e.message);alert(e.message)}finally{dropZone.classList.remove('busy')}}
source.onchange=()=>{if(source.files[0])uploadFile(source.files[0])};$('#chooseFile').onclick=()=>source.click();
['dragenter','dragover'].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove('dragover') }));
dropZone.addEventListener('drop',e=>{if(e.dataTransfer.files[0])uploadFile(e.dataTransfer.files[0])});
document.addEventListener('dragover',e=>{if(e.dataTransfer?.types?.includes('Files'))e.preventDefault()});document.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length){e.preventDefault();uploadFile(e.dataTransfer.files[0])}});
async function restorePending(){try{let j=await api('/editor/pending');if(j.pending){uploadedPath=j.pending.path;uploadedMime=j.pending.mime;uploadedName=j.pending.name;setSourceState(j.pending.name,j.pending.mime);setStatus(window.FARAST_AUTHENTICATED?'فایل قبلی شما آماده ادامه است':'فایل شما حفظ شده است',true)}}catch(e){}}
restorePending();
analyze.onclick=async()=>{if(!uploadedPath){if(source.files[0])await uploadFile(source.files[0]);else return}if(!window.FARAST_AUTHENTICATED){location.href='/login?continue='+encodeURIComponent('/editor');return}setStatus('در حال ارسال به Gemini…');$('#aiStatus').textContent='در حال پردازش';analyze.disabled=true;try{let j=await api('/editor/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:uploadedPath,mime:uploadedMime,source_name:uploadedName})});docId=j.document_id;interactionId=j.interaction_id;requestId=j.request_id;$('#interactionId').textContent=interactionId||'—';$('#requestId').textContent=requestId||'—';$('#aiStatus').textContent='تکمیل شد';renderAi(j);setStatus('رونویسی کامل شد',true);saveNow()}catch(e){$('#aiStatus').textContent='خطا';setStatus(e.message);alert(e.message)}finally{analyze.disabled=!uploadedPath}};
function renderAi(j){editor.innerHTML=j.html||'<p><br></p>';$('#pages').textContent=nf(j.pages);$('#words').textContent=nf(j.text?.trim().split(/\s+/u).filter(Boolean).length);$('#statusWords').textContent=$('#words').textContent;$('#price').textContent=nf(j.price)+' ریال';renderIssues(j.issues||[]);bindUncertain();updatePages();dropZone.classList.add('hidden')}
function renderIssues(xs){$('#issues').innerHTML=xs.length?xs.map(x=>`<div class="issue-card"><mark>${esc(x.word)}</mark><div>${(x.suggestions||[]).map(s=>`<button type="button" data-word="${esc(x.word)}" data-s="${esc(s)}">${esc(s)}</button>`).join('')}</div></div>`).join(''):'<div class="empty-issues">مورد مشکوکی ثبت نشده است.</div>';$$('.issue-card button').forEach(b=>b.onclick=()=>replaceUncertainValue(b.dataset.word,b.dataset.s))}
function bindUncertain(){$$('.ai-uncertain').forEach(el=>el.onclick=e=>{e.stopPropagation();$('#aiWord').textContent=el.dataset.original;let ss=[];try{ss=JSON.parse(el.dataset.suggestions||'[]')}catch{}$('#aiSuggestions').innerHTML=ss.map(s=>`<button data-s="${esc(s)}">${esc(s)}</button>`).join('');$$('#aiSuggestions button').forEach(b=>b.onclick=()=>applySuggestion(el,b.dataset.s));$('#aiPopover').classList.remove('hidden');let r=el.getBoundingClientRect();$('#aiPopover').style.top=(r.bottom+scrollY+8)+'px';$('#aiPopover').style.left=Math.max(20,r.left+scrollX-120)+'px'})}
function applySuggestion(el,s){let original=el.dataset.original;el.replaceWith(document.createTextNode(s));sendFeedback('word_correction',original,s,'ocr_uncertain');$('#aiPopover').classList.add('hidden');scheduleSave()}
function replaceUncertainValue(word,s){let el=$$('.ai-uncertain').find(x=>x.dataset.original===word);if(el)applySuggestion(el,s)}
$('#keepWord').onclick=()=>$('#aiPopover').classList.add('hidden');document.addEventListener('click',e=>{if(!e.target.closest('.ai-popover')&&!e.target.closest('.ai-uncertain'))$('#aiPopover').classList.add('hidden')});
function sendFeedback(type,original='',corrected='',category='',note='',rating=null){if(!docId)return;api('/editor/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:docId,ai_interaction_id:interactionId,type,rating,category,original_text:original,corrected_text:corrected,note,context:{request_id:requestId,editor_version:'word-ribbon-v3'}})}).catch(()=>{})}
$('#rate5').onclick=()=>{sendFeedback('rating','','','','',5);setStatus('بازخورد شما ثبت شد',true)};$('#rate1').onclick=()=>{sendFeedback('rating','','','','',1);setStatus('بازخورد شما ثبت شد',true)};$('#feedbackGood').onclick=()=>{sendFeedback('rating','','','','',5);setStatus('بازخورد ثبت شد',true)};$('#feedbackBad').onclick=()=>{sendFeedback('wrong_output','','','','خروجی OCR نیاز به بررسی انسانی دارد',1);setStatus('بازخورد ثبت شد',true)};$('#feedbackPanelBtn').onclick=()=>$('#aiSidebar').classList.remove('collapsed');
function scheduleSave(){if(!docId)return;$('#saveState').textContent='در حال تغییر…';clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,900)}
async function saveNow(){if(!docId)return;try{let j=await api('/editor/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:docId,content:editor.innerHTML})});setStatus('ذخیره شد',true);return j}catch(e){setStatus('ذخیره ناموفق')}}
$('#saveNow').onclick=saveNow;editor.addEventListener('input',()=>{updateWords();scheduleSave()});
function updateWords(){let t=editor.innerText.trim();$('#statusWords').textContent=nf(t?t.split(/\s+/u).filter(Boolean).length:0)}function updatePages(){let count=Math.max(1,Math.ceil(editor.scrollHeight/1050));$('#totalPages').textContent=nf(count);$('#pages').textContent=nf(count)}
$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);function setZoom(z){zoom=Math.min(1.5,Math.max(.7,z));$('#zoomValue').textContent=Math.round(zoom*100)+'%';$('.word-page').style.transform=`scale(${zoom})`;$('.word-page').style.transformOrigin='top center'}
$('#showAi').onclick=()=>$('#aiSidebar').classList.toggle('collapsed');$('#closeAi').onclick=()=>$('#aiSidebar').classList.add('collapsed');$('#pageBreak').onclick=()=>{editor.focus();document.execCommand('insertHTML',false,'<div class="page-break" contenteditable="false"><span>صفحه جدید</span></div><p><br></p>');scheduleSave()};$('#insertDate').onclick=()=>cmd('insertText',new Intl.DateTimeFormat('fa-IR').format(new Date()));$('#insertLink').onclick=()=>{let u=prompt('نشانی پیوند را وارد کنید');if(u)cmd('createLink',u)};$('#clearLink').onclick=()=>cmd('unlink');$('#pasteText').onclick=async()=>{try{cmd('insertText',await navigator.clipboard.readText())}catch{alert('دسترسی به کلیپ‌بورد توسط مرورگر مسدود شده است.')}};
$('#findText').onclick=()=>{$('#findDialog').classList.remove('hidden');$('#findInput').focus()};$('#replaceText').onclick=()=>{$('#findDialog').classList.remove('hidden');$('#replaceInput').focus()};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#findNext').onclick=()=>{let q=$('#findInput').value;if(q)window.find(q)};$('#replaceOne').onclick=()=>{let q=$('#findInput').value,r=$('#replaceInput').value;if(q&&window.find(q)){document.execCommand('insertText',false,r);scheduleSave()}};$('#replaceAll').onclick=()=>{let q=$('#findInput').value,r=$('#replaceInput').value;if(!q)return;editor.innerHTML=editor.innerHTML.split(q).join(esc(r));scheduleSave()};
$('#exportDocx').onclick=()=>exportDoc('docx');$('#exportPdf').onclick=()=>exportDoc('pdf');async function exportDoc(format){if(!docId)return alert('ابتدا یک فایل را با AI پردازش کنید');await saveNow();let f=document.createElement('form');f.method='POST';f.action='/editor/export/'+format;f.innerHTML='<input type="hidden" name="_token" value="'+csrf+'"><input type="hidden" name="document_id" value="'+docId+'">';document.body.appendChild(f);f.submit()}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang='fa-IR';rec.continuous=true;rec.interimResults=false;$('#mic').onclick=()=>{if($('#mic').classList.toggle('recording')){rec.start();$('#mic').textContent='⏹ توقف صوت'}else rec.stop()};rec.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+' ';if(t){editor.focus();document.execCommand('insertText',false,t);scheduleSave()}};rec.onend=()=>{$('#mic').classList.remove('recording');$('#mic').textContent='🎙 صوت'}}else $('#mic').title='تایپ صوتی داخلی مرورگر در دسترس نیست';
// One editor tab: the first tab owns the editor and asks itself to focus when another tab appears.
const lockKey='farast.editor.lock.v3',tabId=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random());let lock=localStorage.getItem(lockKey),now=Date.now();if(lock){try{let x=JSON.parse(lock);if(x.id!==tabId&&now-(x.time||0)<90000){new BroadcastChannel('farast-editor').postMessage({type:'focus'});setStatus('این ویرایشگر در تب دیگری باز است');dropZone.classList.add('locked');analyze.disabled=true;return;}}catch{}}
localStorage.setItem(lockKey,JSON.stringify({id:tabId,time:now,url:location.href}));const bc=new BroadcastChannel('farast-editor');bc.onmessage=e=>{if(e.data?.type==='focus'){window.focus();bc.postMessage({type:'focused'});}};const lockTimer=setInterval(()=>localStorage.setItem(lockKey,JSON.stringify({id:tabId,time:Date.now(),url:location.href})),15000);window.addEventListener('beforeunload',()=>{clearInterval(lockTimer);try{let x=JSON.parse(localStorage.getItem(lockKey)||'{}');if(x.id===tabId)localStorage.removeItem(lockKey)}catch{}});
setInterval(()=>{if(window.FARAST_AUTHENTICATED)fetch('/editor/heartbeat',{method:'POST',headers:{'X-CSRF-TOKEN':csrf}})},60000);updateWords();
})();
</script>
@endpush
