@extends('layouts.app')
@section('content')
@if($announcements->count())<section class="home-announcements" dir="rtl"><div class="home-announcement-label"><i class="fa-solid fa-bullhorn"></i><b>آخرین اطلاعیه</b></div><div class="home-announcement-main"><strong>{{ $announcements->first()->title }}</strong><span>{{ \Illuminate\Support\Str::limit($announcements->first()->body, 150) }}</span></div><a href="/announcements">همه اعلانات <i class="fa-solid fa-arrow-left"></i></a></section>@endif
<section class="hero" id="start"><div class="hero-copy"><span class="eyebrow">تایپ آنلاین با هوش مصنوعی</span><h1>فایل را رها کن؛ متن مرتب و آماده ویرایش تحویل بگیر</h1><p>تصویر، PDF یا ZIP تصاویر را وارد کنید. فراست ساختار پاراگراف‌ها، فارسی و انگلیسی و علائم قابل تشخیص را حفظ می‌کند و خروجی Word و PDF می‌دهد.</p><div class="actions"><a class="btn primary" href="/editor"><i class="fa-solid fa-wand-magic-sparkles"></i> شروع تایپ</a><a class="btn ghost" href="/pricing"><i class="fa-solid fa-tags"></i> مشاهده نرخنامه</a></div><div class="hero-trust"><span><i class="fa-solid fa-shield-halved"></i> فایل خصوصی</span><span><i class="fa-solid fa-file-word"></i> خروجی Word</span><span><i class="fa-solid fa-bolt"></i> پردازش هوشمند</span></div></div><div class="hero-card premium-upload-card"><div class="upload-home" id="homeDrop"><div class="upload-orbit"><span><i class="fa-solid fa-cloud-arrow-up"></i></span><i class="fa-solid fa-sparkles orbit-spark"></i></div><strong>فایل را بکشید و اینجا رها کنید</strong><span>تصویر، PDF یا ZIP</span><button type="button" id="homeChoose"><i class="fa-solid fa-folder-open"></i> انتخاب فایل</button><input id="homeFile" type="file" accept="image/*,.pdf,.zip" hidden></div><div id="homeMsg" class="home-upload-msg" hidden></div><small><i class="fa-solid fa-gift"></i> برای تست، یک صفحه رایگان در اختیار شماست.</small></div></section>
<section class="features"><article><span class="feature-icon"><i class="fa-solid fa-file-pen"></i></span><b>ساده مثل Word</b><span>صفحه A4، فونت B Nazanin با اندازه ۱۶ و محیط ویرایش شبیه Word.</span></article><article><span class="feature-icon"><i class="fa-solid fa-eye"></i></span><b>OCR دقیق</b><span>Gemini متن را رونویسی می‌کند و واژه‌های مشکوک را برای بررسی کاربر مشخص می‌کند.</span></article><article><span class="feature-icon"><i class="fa-solid fa-file-export"></i></span><b>خروجی مرتب</b><span>Word و PDF با قالب پایه یکسان تولید می‌شوند و هایلایت‌های عیب‌یابی در خروجی نهایی عادی می‌شوند.</span></article><article><span class="feature-icon"><i class="fa-solid fa-user-shield"></i></span><b>حریم خصوصی</b><span>فایل‌ها خصوصی و موقت نگه‌داری می‌شوند و اطلاعات شخصی شما برای مدل ارسال نمی‌شود.</span></article></section>
<section class="home-steps"><div><b>۱</b><span>فایل را انتخاب یا رها کنید</span></div><div><b>۲</b><span>در صورت نیاز وارد حساب شوید؛ فایل از بین نمی‌رود</span></div><div><b>۳</b><span>رونویسی، بررسی و ویرایش کنید</span></div><div><b>۴</b><span>Word یا PDF دریافت کنید</span></div></section>
@endsection
@push('scripts')
<style>.home-announcements{max-width:1100px;margin:18px auto 0;padding:0 18px;display:flex;align-items:center;gap:13px}.home-announcement-label{display:flex;align-items:center;gap:7px;padding:10px 12px;border-radius:11px;background:#eef4ff;color:#1769ff;font-size:10px;white-space:nowrap}.home-announcement-main{display:flex;gap:9px;align-items:center;flex:1;min-width:0}.home-announcement-main strong{font-size:11px;color:#243a5a}.home-announcement-main span{font-size:10px;color:#8290a4;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.home-announcements>a{font-size:9px;color:#1769ff;text-decoration:none;white-space:nowrap}.premium-upload-card{overflow:hidden;position:relative}.premium-upload-card:before{content:"";position:absolute;inset:-100px;background:radial-gradient(circle,rgba(23,105,255,.12),transparent 45%);pointer-events:none}.upload-home{position:relative;z-index:1}.upload-orbit{width:78px;height:78px;position:relative;display:grid;place-items:center;margin-bottom:5px}.upload-orbit>span{width:58px;height:58px;border-radius:18px;background:#edf4ff;color:#1769ff;display:grid;place-items:center;font-size:24px;box-shadow:0 12px 30px rgba(23,105,255,.14)}.orbit-spark{position:absolute;right:3px;top:4px;color:#7a5cff;font-size:13px;animation:sparkFloat 2.2s ease-in-out infinite}.hero-trust{display:flex;flex-wrap:wrap;gap:12px;margin-top:19px;color:#7f8da1;font-size:9px}.hero-trust span{display:flex;align-items:center;gap:5px}.hero-trust i{color:#1769ff}.feature-icon{width:38px;height:38px;border-radius:12px;background:#eef4ff;color:#1769ff;display:grid;place-items:center;margin-bottom:11px}.features article{display:flex;flex-direction:column;align-items:flex-start}.features article>span:last-child{margin-top:6px}.upload-home button{position:relative;z-index:2;display:flex;align-items:center;gap:7px}@keyframes sparkFloat{50%{transform:translateY(-5px) rotate(8deg)}}@media(max-width:700px){.home-announcements{display:none}.hero-trust{gap:8px}}
</style>
<script>(()=>{const d=document.getElementById('homeDrop'),f=document.getElementById('homeFile'),c=document.getElementById('homeChoose'),m=document.getElementById('homeMsg'),token=document.querySelector('meta[name=csrf-token]');if(!d)return;c.onclick=()=>f.click();['dragenter','dragover'].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.classList.add('dragover')}));['dragleave','drop'].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.classList.remove('dragover')}));d.addEventListener('drop',e=>{if(e.dataTransfer.files[0])send(e.dataTransfer.files[0])});f.onchange=()=>{if(f.files[0])send(f.files[0])};async function send(file){m.hidden=false;m.textContent='در حال آماده‌سازی فایل…';const fd=new FormData();fd.append('source',file);try{const r=await fetch('/editor/upload',{method:'POST',headers:{'X-CSRF-TOKEN':token?.content||'','Accept':'application/json'},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.message||'آپلود ناموفق بود');m.textContent='فایل آماده شد؛ در حال ورود به ویرایشگر…';location.href='/editor'}catch(e){m.textContent=e.message}}})();</script>
@endpush
