@extends('layouts.app')
@section('content')
<section class="hero" id="start">
  <div class="hero-copy"><span class="eyebrow">تایپ آنلاین با هوش مصنوعی</span><h1>فایل را رها کن؛ متن مرتب و آماده ویرایش تحویل بگیر</h1><p>تصویر، PDF یا ZIP تصاویر را وارد کنید. فراست ساختار پاراگراف‌ها، فارسی و انگلیسی و علائم قابل تشخیص را حفظ می‌کند و خروجی Word و PDF می‌دهد.</p><div class="actions"><a class="btn primary" href="/editor">شروع تایپ</a><a class="btn ghost" href="/pricing">مشاهده نرخنامه</a></div></div>
  <div class="hero-card"><div class="upload-home" id="homeDrop"><div class="upload-home-icon">↑</div><strong>فایل را بکشید و اینجا رها کنید</strong><span>تصویر، PDF یا ZIP</span><button type="button" id="homeChoose">انتخاب فایل</button><input id="homeFile" type="file" accept="image/*,.pdf,.zip" hidden></div><div id="homeMsg" class="home-upload-msg" hidden></div><small>برای تست، یک صفحه رایگان در اختیار شماست.</small></div>
</section>
<section class="features"><article><b>ساده مثل Word</b><span>صفحه A4، فونت B Nazanin با اندازه ۱۶ و محیط ویرایش شبیه Word.</span></article><article><b>OCR دقیق</b><span>Gemini متن را رونویسی می‌کند و واژه‌های مشکوک را برای بررسی کاربر مشخص می‌کند.</span></article><article><b>خروجی مرتب</b><span>Word و PDF با قالب پایه یکسان تولید می‌شوند و هایلایت‌های عیب‌یابی در خروجی نهایی عادی می‌شوند.</span></article><article><b>حریم خصوصی</b><span>فایل‌ها خصوصی و موقت نگه‌داری می‌شوند و اطلاعات شخصی شما برای مدل ارسال نمی‌شود.</span></article></section>
<section class="home-steps"><div><b>۱</b><span>فایل را انتخاب یا رها کنید</span></div><div><b>۲</b><span>در صورت نیاز وارد حساب شوید؛ فایل از بین نمی‌رود</span></div><div><b>۳</b><span>رونویسی، بررسی و ویرایش کنید</span></div><div><b>۴</b><span>Word یا PDF دریافت کنید</span></div></section>
@endsection
@push('scripts')
<style>.upload-home{min-height:250px;border:2px dashed #a9b4c4;border-radius:18px;background:#f8fafc;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;padding:18px;transition:.15s}.upload-home.dragover{border-color:#1769ff;background:#eef5ff}.upload-home-icon{font:34px Arial;color:#1769ff}.upload-home strong{font-size:17px}.upload-home span{color:#778397;font-size:12px}.upload-home button{border:1px solid #cbd4df;background:#fff;border-radius:9px;padding:8px 16px;font:13px inherit;cursor:pointer}.home-upload-msg{margin-top:10px;padding:9px;border-radius:9px;background:#eef4ff;color:#235ca9;font-size:12px}.home-steps{max-width:1100px;margin:28px auto 50px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:0 18px}.home-steps div{background:#fff;border:1px solid #e3e7ed;border-radius:14px;padding:16px;display:flex;align-items:center;gap:10px}.home-steps b{width:30px;height:30px;border-radius:50%;background:#eef4ff;color:#1769ff;display:grid;place-items:center}.home-steps span{font-size:13px}@media(max-width:800px){.home-steps{grid-template-columns:1fr 1fr}}</style>
<script>(()=>{const d=document.getElementById('homeDrop'),f=document.getElementById('homeFile'),c=document.getElementById('homeChoose'),m=document.getElementById('homeMsg'),csrf=document.querySelector('meta[name=csrf-token]').content;if(!d)return;c.onclick=()=>f.click();['dragenter','dragover'].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.classList.add('dragover')}));['dragleave','drop'].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.classList.remove('dragover')}));d.addEventListener('drop',e=>{if(e.dataTransfer.files[0])send(e.dataTransfer.files[0])});f.onchange=()=>{if(f.files[0])send(f.files[0])};async function send(file){m.hidden=false;m.textContent='در حال آماده‌سازی فایل…';const fd=new FormData();fd.append('source',file);try{const r=await fetch('/editor/upload',{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.message||'آپلود ناموفق بود');m.textContent='فایل آماده شد؛ در حال ورود به ویرایشگر…';location.href='/editor'}catch(e){m.textContent=e.message}}})();</script>
@endpush
