@extends('layouts.app')
@section('content')
<div class="container" dir="rtl" style="max-width:1250px;padding:38px 20px 70px">
<header class="page-head"><div><span class="eyebrow"><i class="fa-solid fa-store"></i> مدیریت فروشگاه</span><h1>کاتالوگ و محصولات دیجیتال</h1><p>دسته‌بندی، قیمت، فایل خصوصی، پیش‌نمایش و پارامترهای محصول را از یک فضای واقعی مدیریت کنید.</p></div><a class="btn outline" href="{{ route('admin.index') }}"><i class="fa-solid fa-arrow-right"></i> بازگشت به مدیریت</a></header>
<div class="cards" style="margin-bottom:18px"><div><b>{{ $products->total() }}</b><span>محصول</span></div><div><b>{{ $categories->count() }}</b><span>دسته‌بندی</span></div><div><b>{{ $products->where('status','published')->count() }}</b><span>منتشرشده در صفحه جاری</span></div></div>
<div class="admin-section-grid">
<section class="panel" style="padding:22px"><div class="panel-heading"><div><h2>دسته‌بندی جدید</h2><p>ساختار سلسله‌مراتبی واقعی برای کاتالوگ.</p></div></div><form method="POST" action="{{ route('admin.store.categories.create') }}" class="account-form">@csrf<label>نام<input name="name" required maxlength="160"></label><label>Slug<input name="slug" dir="ltr" pattern="[a-z0-9-]+" placeholder="digital-templates"></label><label>دسته والد<select name="parent_id"><option value="">بدون والد</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>ترتیب<input type="number" name="sort_order" value="0" min="0"></label><label class="full">توضیح<textarea name="description" rows="3"></textarea></label><button class="btn primary"><i class="fa-solid fa-plus"></i> ایجاد دسته</button></form></section>
<section class="panel" style="padding:22px"><div class="panel-heading"><div><h2>محصول دیجیتال جدید</h2><p>فایل اصلی در دیسک private ذخیره می‌شود و پارامترها JSON معتبر هستند.</p></div></div><form method="POST" action="{{ route('admin.store.products.create') }}" enctype="multipart/form-data" class="account-form">@csrf<label>عنوان<input name="title" required maxlength="220"></label><label>Slug<input name="slug" dir="ltr" pattern="[a-z0-9-]+"></label><label>دسته‌بندی<select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>SKU<input name="sku" dir="ltr"></label><label>قیمت (ریال)<input type="number" name="price_rials" min="0" required></label><label>تخفیف درصدی<input type="number" name="discount_percent" min="0" max="100" step="0.01" value="0"></label><label>قیمت قبل از تخفیف<input type="number" name="compare_at_price_rials" min="0"></label><label>نسخه<input name="version" maxlength="60" placeholder="1.0.0"></label><label>سیاست پیش‌نمایش<select name="preview_policy"><option value="limited">محدود</option><option value="none">بدون پیش‌نمایش</option><option value="full">کامل</option></select></label><label>تعداد صفحات پیش‌نمایش<input type="number" name="preview_pages" value="3" min="0"></label><label>سیاست دانلود<select name="download_policy"><option value="signed">لینک امضاشده</option><option value="limited">محدودشده</option></select></label><label>حد دانلود<input type="number" name="download_limit" min="1"></label><label>نوع مجوز<input name="license_type" value="standard"></label><label>وضعیت<select name="status"><option value="draft">پیش‌نویس</option><option value="published">منتشرشده</option></select></label><label>تصویر جلد<input type="file" name="cover" accept="image/*"></label><label>فایل اصلی<input type="file" name="file" required accept=".pdf,.doc,.docx,.zip,.rar,.txt"></label><label>پیش‌نمایش<input type="file" name="preview_file" accept=".pdf,image/*"></label><label class="full">توضیح کوتاه<textarea name="short_description" rows="2"></textarea></label><label class="full">توضیح کامل<textarea name="description" rows="4"></textarea></label><label class="full">پارامترهای محصول (JSON)<textarea name="parameters" rows="4" dir="ltr" placeholder='[{"name":"format","label":"فرمت","type":"select","required":true,"readonly":false,"options":["PDF","Word"]}]'></textarea></label><label class="full">SEO description<textarea name="seo_description" rows="2" maxlength="320"></textarea></label><label class="preference"><span>محصول ویژه</span><input type="checkbox" name="featured" value="1"><b></b></label><button class="btn primary"><i class="fa-solid fa-cloud-arrow-up"></i> ثبت محصول و فایل خصوصی</button></form></section>
</div>
<section class="panel" style="padding:22px;margin-top:18px"><div class="panel-heading"><div><h2>کاتالوگ فعلی</h2><p>فایل‌ها و وضعیت انتشار بدون افشای مسیر خصوصی نمایش داده می‌شوند.</p></div></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:right;padding:10px">محصول</th><th>دسته</th><th>قیمت</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($products as $product)<tr><td style="padding:10px"><b>{{ $product->title }}</b><small style="display:block;color:#64748b">{{ $product->sku }} · v{{ $product->version ?: '—' }}</small></td><td>{{ $product->category?->name }}</td><td>{{ number_format($product->price_rials) }} ریال</td><td>{{ $product->status === 'published' ? 'منتشر' : 'پیش‌نویس' }}</td><td><form method="POST" action="{{ route('admin.store.products.toggle',$product) }}">@csrf<button class="btn outline" type="submit">{{ $product->status === 'published' ? 'لغو انتشار' : 'انتشار' }}</button></form></td></tr>@empty<tr><td colspan="5" style="padding:20px;text-align:center">هنوز محصولی ثبت نشده است.</td></tr>@endforelse</tbody></table></div>{{ $products->links() }}</section>
</div>
@endsection
