<?php

return [
    'navigation' => [
        [
            'key' => 'workspace', 'label' => 'میز کار', 'icon' => 'fa-table-cells-large',
            'items' => [
                ['key' => 'workspace.overview', 'label' => 'نمای کلی', 'icon' => 'fa-grid-2', 'route' => 'dashboard'],
                ['key' => 'workspace.recent', 'label' => 'فعالیت‌های اخیر', 'icon' => 'fa-clock-rotate-left', 'route' => 'workspace.recent'],
                ['key' => 'workspace.tasks', 'label' => 'وظایف من', 'icon' => 'fa-list-check', 'route' => 'workspace.tasks'],
                ['key' => 'workspace.action', 'label' => 'موارد نیازمند اقدام', 'icon' => 'fa-bell-exclamation', 'route' => 'workspace.actions'],
                ['key' => 'workspace.shortcuts', 'label' => 'میانبرها', 'icon' => 'fa-bolt', 'route' => 'workspace.shortcuts'],
                ['key' => 'workspace.wallet', 'label' => 'کیف پول', 'icon' => 'fa-wallet', 'route' => 'wallet'],
                ['key' => 'workspace.status', 'label' => 'وضعیت سیستم', 'icon' => 'fa-heart-pulse', 'route' => 'admin.index', 'fragment' => '#operations', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'documents', 'label' => 'اسناد و فایل‌ها', 'icon' => 'fa-folder-open',
            'items' => [
                ['key' => 'documents.all', 'label' => 'همه اسناد', 'icon' => 'fa-files', 'route' => 'documents.all', 'admin_only' => true],
                ['key' => 'documents.mine', 'label' => 'اسناد من', 'icon' => 'fa-file-lines', 'route' => 'documents.mine', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.recent', 'label' => 'اسناد اخیر', 'icon' => 'fa-clock-rotate-left', 'route' => 'documents.recent', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.files', 'label' => 'فایل‌ها', 'icon' => 'fa-folder', 'route' => 'library', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.folders', 'label' => 'پوشه‌ها', 'icon' => 'fa-folder-tree', 'route' => 'modules.show', 'route_params' => ['slug' => 'folders'], 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.shared', 'label' => 'اشتراک‌گذاری‌ها', 'icon' => 'fa-share-nodes', 'route' => 'modules.show', 'route_params' => ['slug' => 'shared']],
                ['key' => 'documents.deleted', 'label' => 'موارد حذف‌شده', 'icon' => 'fa-trash-can', 'route' => 'documents.deleted', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.archive', 'label' => 'بایگانی', 'icon' => 'fa-box-archive', 'route' => 'modules.show', 'route_params' => ['slug' => 'archive']],
            ],
        ],
        [
            'key' => 'editor', 'label' => 'ویرایشگر', 'icon' => 'fa-pen-ruler',
            'items' => [
                ['key' => 'editor.start', 'label' => 'ویرایشگر', 'icon' => 'fa-pen-to-square', 'route' => 'editor', 'permission' => 'editor.use', 'scope' => 'own'],
                ['key' => 'editor.recent', 'label' => 'اسناد اخیر', 'icon' => 'fa-clock-rotate-left', 'route' => 'documents.recent', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'editor.templates', 'label' => 'قالب‌ها', 'icon' => 'fa-layer-group', 'route' => 'modules.show', 'route_params' => ['slug' => 'templates']],
                ['key' => 'editor.drafts', 'label' => 'پیش‌نویس‌ها', 'icon' => 'fa-file-pen', 'route' => 'documents.drafts', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'editor.favorites', 'label' => 'موارد مورد علاقه', 'icon' => 'fa-star', 'route' => 'modules.show', 'route_params' => ['slug' => 'favorites']],
            ],
        ],
        [
            'key' => 'automation', 'label' => 'اتوماسیون و گردش کار', 'icon' => 'fa-diagram-project',
            'items' => [
                ['key' => 'automation.workflows', 'label' => 'گردش‌های کار', 'icon' => 'fa-route', 'route' => 'modules.show', 'route_params' => ['slug' => 'workflows']],
                ['key' => 'automation.processes', 'label' => 'فرآیندها', 'icon' => 'fa-diagram-next', 'route' => 'modules.show', 'route_params' => ['slug' => 'processes']],
                ['key' => 'automation.rules', 'label' => 'قوانین', 'icon' => 'fa-filter-circle-dollar', 'route' => 'modules.show', 'route_params' => ['slug' => 'rules']],
                ['key' => 'automation.actions', 'label' => 'اقدامات خودکار', 'icon' => 'fa-bolt-lightning', 'route' => 'modules.show', 'route_params' => ['slug' => 'auto-actions']],
                ['key' => 'automation.runs', 'label' => 'اجرای‌های اخیر', 'icon' => 'fa-clock-rotate-left', 'route' => 'modules.show', 'route_params' => ['slug' => 'runs']],
                ['key' => 'automation.queue', 'label' => 'صف‌ها / اجرای‌ها', 'icon' => 'fa-bars-progress', 'route' => 'modules.show', 'route_params' => ['slug' => 'queues']],
                ['key' => 'automation.errors', 'label' => 'خطاهای اجرای فرآیند', 'icon' => 'fa-triangle-exclamation', 'route' => 'modules.show', 'route_params' => ['slug' => 'run-errors']],
            ],
        ],
        [
            'key' => 'ai', 'label' => 'هوش مصنوعی', 'icon' => 'fa-wand-magic-sparkles',
            'items' => [
                ['key' => 'ai.assistant', 'label' => 'دستیار هوشمند', 'icon' => 'fa-message-bot', 'route' => 'editor', 'permission' => 'ai.use', 'scope' => 'own'],
                ['key' => 'ai.tools', 'label' => 'ابزارهای AI', 'icon' => 'fa-sparkles', 'route' => 'editor', 'permission' => 'ai.use', 'scope' => 'own'],
                ['key' => 'ai.analytics', 'label' => 'تحلیل‌ها', 'icon' => 'fa-chart-line', 'route' => 'modules.show', 'route_params' => ['slug' => 'ai-analytics']],
                ['key' => 'ai.suggestions', 'label' => 'پیشنهادها', 'icon' => 'fa-lightbulb', 'route' => 'modules.show', 'route_params' => ['slug' => 'ai-suggestions']],
                ['key' => 'ai.history', 'label' => 'تاریخچه عملیات AI', 'icon' => 'fa-clock-rotate-left', 'route' => 'ai.history', 'permission' => 'ai.use', 'scope' => 'own'],
                ['key' => 'ai.settings', 'label' => 'تنظیمات AI', 'icon' => 'fa-sliders', 'route' => 'admin.index', 'fragment' => '#ai-settings', 'admin_only' => true],
                ['key' => 'ai.quota', 'label' => 'مصرف و سهمیه AI', 'icon' => 'fa-gauge-high', 'route' => 'ai.quota', 'permission' => 'ai.use', 'scope' => 'own'],
            ],
        ],
        [
            'key' => 'collaboration', 'label' => 'تیم و همکاری', 'icon' => 'fa-people-group',
            'items' => [
                ['key' => 'collaboration.members', 'label' => 'اعضای تیم', 'icon' => 'fa-users', 'route' => 'modules.show', 'route_params' => ['slug' => 'team-members']],
                ['key' => 'collaboration.teams', 'label' => 'تیم‌ها', 'icon' => 'fa-users-rectangle', 'route' => 'modules.show', 'route_params' => ['slug' => 'teams']],
                ['key' => 'collaboration.invites', 'label' => 'دعوت‌ها', 'icon' => 'fa-user-plus', 'route' => 'modules.show', 'route_params' => ['slug' => 'invites']],
                ['key' => 'collaboration.shared', 'label' => 'اشتراک‌گذاری', 'icon' => 'fa-share-nodes', 'route' => 'modules.show', 'route_params' => ['slug' => 'collab-shared']],
                ['key' => 'collaboration.work', 'label' => 'همکاری‌ها', 'icon' => 'fa-handshake', 'route' => 'modules.show', 'route_params' => ['slug' => 'collab-work']],
                ['key' => 'collaboration.activity', 'label' => 'فعالیت تیم', 'icon' => 'fa-chart-simple', 'route' => 'modules.show', 'route_params' => ['slug' => 'team-activity']],
                ['key' => 'collaboration.requests', 'label' => 'درخواست‌ها', 'icon' => 'fa-inbox', 'route' => 'modules.show', 'route_params' => ['slug' => 'team-requests']],
            ],
        ],
        [
            'key' => 'reports', 'label' => 'گزارش‌ها و تحلیل‌ها', 'icon' => 'fa-chart-pie',
            'items' => [
                ['key' => 'reports.overview', 'label' => 'گزارش کلی', 'icon' => 'fa-chart-column', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-overview']],
                ['key' => 'reports.users', 'label' => 'فعالیت کاربران', 'icon' => 'fa-user-chart', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-users'], 'admin_only' => true],
                ['key' => 'reports.team', 'label' => 'عملکرد تیم', 'icon' => 'fa-people-group', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-team']],
                ['key' => 'reports.documents', 'label' => 'اسناد', 'icon' => 'fa-file-chart-column', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-documents']],
                ['key' => 'reports.workflows', 'label' => 'گردش کار', 'icon' => 'fa-route', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-workflows']],
                ['key' => 'reports.ai', 'label' => 'AI', 'icon' => 'fa-wand-magic-sparkles', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-ai']],
                ['key' => 'reports.resources', 'label' => 'مصرف منابع', 'icon' => 'fa-gauge', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-resources'], 'admin_only' => true],
                ['key' => 'reports.finance', 'label' => 'گزارش‌های مالی', 'icon' => 'fa-wallet', 'route' => 'admin.finance', 'admin_only' => true],
                ['key' => 'reports.system', 'label' => 'گزارش‌های سیستمی', 'icon' => 'fa-server', 'route' => 'modules.show', 'route_params' => ['slug' => 'reports-system'], 'admin_only' => true],
            ],
        ],
        [
            'key' => 'notifications', 'label' => 'اعلان‌ها و پیام‌ها', 'icon' => 'fa-bell',
            'items' => [
                ['key' => 'notifications.alerts', 'label' => 'اعلان‌ها', 'icon' => 'fa-bell', 'route' => 'announcements'],
                ['key' => 'notifications.messages', 'label' => 'پیام‌ها', 'icon' => 'fa-messages', 'route' => 'modules.show', 'route_params' => ['slug' => 'messages']],
                ['key' => 'notifications.notices', 'label' => 'اطلاعیه‌ها', 'icon' => 'fa-bullhorn', 'route' => 'announcements'],
                ['key' => 'notifications.activity', 'label' => 'فعالیت‌ها', 'icon' => 'fa-list-check', 'route' => 'modules.show', 'route_params' => ['slug' => 'activity-feed']],
                ['key' => 'notifications.settings', 'label' => 'تنظیمات اعلان', 'icon' => 'fa-sliders', 'route' => 'modules.show', 'route_params' => ['slug' => 'notification-settings']],
            ],
        ],
        [
            'key' => 'access', 'label' => 'مدیریت کاربران و دسترسی‌ها', 'icon' => 'fa-user-shield', 'admin_only' => true,
            'items' => [
                ['key' => 'access.users', 'label' => 'کاربران', 'icon' => 'fa-users', 'route' => 'admin.index', 'fragment' => '#users', 'admin_only' => true],
                ['key' => 'access.roles', 'label' => 'نقش‌ها', 'icon' => 'fa-id-badge', 'route' => 'modules.show', 'route_params' => ['slug' => 'roles'], 'admin_only' => true],
                ['key' => 'access.permissions', 'label' => 'مجوزها', 'icon' => 'fa-key', 'route' => 'modules.show', 'route_params' => ['slug' => 'permissions'], 'admin_only' => true],
                ['key' => 'access.groups', 'label' => 'گروه‌ها', 'icon' => 'fa-layer-group', 'route' => 'modules.show', 'route_params' => ['slug' => 'groups'], 'admin_only' => true],
                ['key' => 'access.teams', 'label' => 'تیم‌ها', 'icon' => 'fa-users-rectangle', 'route' => 'modules.show', 'route_params' => ['slug' => 'access-teams'], 'admin_only' => true],
                ['key' => 'access.requests', 'label' => 'درخواست‌های دسترسی', 'icon' => 'fa-user-clock', 'route' => 'modules.show', 'route_params' => ['slug' => 'access-requests'], 'admin_only' => true],
                ['key' => 'access.activity', 'label' => 'فعالیت کاربران', 'icon' => 'fa-list-check', 'route' => 'modules.show', 'route_params' => ['slug' => 'user-activity'], 'admin_only' => true],
                ['key' => 'access.sessions', 'label' => 'نشست‌ها', 'icon' => 'fa-display', 'route' => 'modules.show', 'route_params' => ['slug' => 'sessions'], 'admin_only' => true],
                ['key' => 'access.status', 'label' => 'وضعیت حساب‌ها', 'icon' => 'fa-user-check', 'route' => 'modules.show', 'route_params' => ['slug' => 'account-status'], 'admin_only' => true],
            ],
        ],
        [
            'key' => 'organization', 'label' => 'مدیریت سازمان', 'icon' => 'fa-building', 'admin_only' => true,
            'items' => [
                ['key' => 'organization.info', 'label' => 'اطلاعات سازمان', 'icon' => 'fa-building', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-info'], 'admin_only' => true],
                ['key' => 'organization.structure', 'label' => 'ساختار سازمانی', 'icon' => 'fa-sitemap', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-structure'], 'admin_only' => true],
                ['key' => 'organization.units', 'label' => 'واحدها', 'icon' => 'fa-diagram-project', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-units'], 'admin_only' => true],
                ['key' => 'organization.teams', 'label' => 'تیم‌ها', 'icon' => 'fa-users-rectangle', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-teams'], 'admin_only' => true],
                ['key' => 'organization.members', 'label' => 'اعضا', 'icon' => 'fa-users', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-members'], 'admin_only' => true],
                ['key' => 'organization.policies', 'label' => 'سیاست‌ها', 'icon' => 'fa-shield-halved', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-policies'], 'admin_only' => true],
                ['key' => 'organization.settings', 'label' => 'تنظیمات سازمان', 'icon' => 'fa-gear', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-settings'], 'admin_only' => true],
                ['key' => 'organization.brand', 'label' => 'برند سازمان', 'icon' => 'fa-palette', 'route' => 'modules.show', 'route_params' => ['slug' => 'org-brand'], 'admin_only' => true],
            ],
        ],
        [
            'key' => 'security', 'label' => 'امنیت و نظارت', 'icon' => 'fa-shield-halved', 'admin_only' => true,
            'items' => [
                ['key' => 'security.report', 'label' => 'گزارش امنیتی', 'icon' => 'fa-file-shield', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-report'], 'admin_only' => true],
                ['key' => 'security.sensitive', 'label' => 'فعالیت‌های حساس', 'icon' => 'fa-user-lock', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-sensitive'], 'admin_only' => true],
                ['key' => 'security.logs', 'label' => 'لاگ‌ها', 'icon' => 'fa-list', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-logs'], 'admin_only' => true],
                ['key' => 'security.sessions', 'label' => 'نشست‌ها', 'icon' => 'fa-display', 'route' => 'modules.show', 'route_params' => ['slug' => 'sessions'], 'admin_only' => true],
                ['key' => 'security.logins', 'label' => 'ورودها', 'icon' => 'fa-right-to-bracket', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-logins'], 'admin_only' => true],
                ['key' => 'security.events', 'label' => 'رویدادهای امنیتی', 'icon' => 'fa-triangle-exclamation', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-events'], 'admin_only' => true],
                ['key' => 'security.access', 'label' => 'دسترسی‌های حساس', 'icon' => 'fa-key', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-access'], 'admin_only' => true],
                ['key' => 'security.status', 'label' => 'وضعیت سیستم', 'icon' => 'fa-server', 'route' => 'admin.index', 'fragment' => '#operations', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'settings', 'label' => 'تنظیمات و پشتیبانی', 'icon' => 'fa-gear',
            'items' => [
                ['key' => 'settings.account', 'label' => 'تنظیمات حساب', 'icon' => 'fa-user-gear', 'route' => 'account.show'],
                ['key' => 'settings.general', 'label' => 'تنظیمات عمومی', 'icon' => 'fa-sliders', 'route' => 'admin.index', 'fragment' => '#settings', 'admin_only' => true],
                ['key' => 'settings.ui', 'label' => 'تنظیمات رابط کاربری', 'icon' => 'fa-display', 'route' => 'modules.show', 'route_params' => ['slug' => 'ui-settings']],
                ['key' => 'settings.notifications', 'label' => 'اعلان‌ها', 'icon' => 'fa-bell', 'route' => 'modules.show', 'route_params' => ['slug' => 'notification-settings']],
                ['key' => 'settings.security', 'label' => 'امنیت', 'icon' => 'fa-lock', 'route' => 'modules.show', 'route_params' => ['slug' => 'security-settings']],
                ['key' => 'settings.wallet', 'label' => 'کیف پول', 'icon' => 'fa-wallet', 'route' => 'wallet'],
                ['key' => 'settings.finance', 'label' => 'مالی (ادمین)', 'icon' => 'fa-money-bill-transfer', 'route' => 'admin.finance', 'admin_only' => true],
                ['key' => 'settings.email', 'label' => 'ایمیل', 'icon' => 'fa-envelope', 'route' => 'admin.emails', 'admin_only' => true],
                ['key' => 'settings.support', 'label' => 'پشتیبانی', 'icon' => 'fa-headset', 'route' => 'support', 'permission' => 'support.use', 'scope' => 'own'],
                ['key' => 'settings.help', 'label' => 'راهنما', 'icon' => 'fa-circle-question', 'route' => 'modules.show', 'route_params' => ['slug' => 'help']],
                ['key' => 'settings.about', 'label' => 'درباره سیستم', 'icon' => 'fa-circle-info', 'route' => 'modules.show', 'route_params' => ['slug' => 'about']],
            ],
        ],
    ],
];
