<?php

return [
    'navigation' => [
        [
            'key' => 'workspace', 'label' => 'میز کار', 'icon' => 'fa-table-cells-large',
            'items' => [
                ['key' => 'workspace.overview', 'label' => 'نمای کلی', 'icon' => 'fa-grid-2', 'route' => 'dashboard'],
                ['key' => 'workspace.recent', 'label' => 'فعالیت‌های اخیر', 'icon' => 'fa-clock-rotate-left', 'planned' => true],
                ['key' => 'workspace.tasks', 'label' => 'وظایف من', 'icon' => 'fa-list-check', 'planned' => true],
                ['key' => 'workspace.action', 'label' => 'موارد نیازمند اقدام', 'icon' => 'fa-bell-exclamation', 'planned' => true],
                ['key' => 'workspace.shortcuts', 'label' => 'میانبرها', 'icon' => 'fa-bolt', 'planned' => true],
                ['key' => 'workspace.status', 'label' => 'وضعیت سیستم', 'icon' => 'fa-heart-pulse', 'route' => 'admin.index', 'fragment' => '#operations', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'documents', 'label' => 'اسناد و فایل‌ها', 'icon' => 'fa-folder-open',
            'items' => [
                ['key' => 'documents.all', 'label' => 'همه اسناد', 'icon' => 'fa-files', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'documents.mine', 'label' => 'اسناد من', 'icon' => 'fa-file-lines', 'route' => 'dashboard', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.recent', 'label' => 'اسناد اخیر', 'icon' => 'fa-clock-rotate-left', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.files', 'label' => 'فایل‌ها', 'icon' => 'fa-folder', 'route' => 'library', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.folders', 'label' => 'پوشه‌ها', 'icon' => 'fa-folder-tree', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.shared', 'label' => 'اشتراک‌گذاری‌ها', 'icon' => 'fa-share-nodes', 'planned' => true, 'permission' => 'documents.share', 'scope' => 'team'],
                ['key' => 'documents.deleted', 'label' => 'موارد حذف‌شده', 'icon' => 'fa-trash-can', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'documents.archive', 'label' => 'بایگانی', 'icon' => 'fa-box-archive', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'own'],
            ],
        ],
        [
            'key' => 'editor', 'label' => 'ویرایشگر', 'icon' => 'fa-pen-ruler',
            'items' => [
                ['key' => 'editor.start', 'label' => 'ویرایشگر', 'icon' => 'fa-pen-to-square', 'route' => 'editor', 'permission' => 'editor.use', 'scope' => 'own'],
                ['key' => 'editor.recent', 'label' => 'اسناد اخیر', 'icon' => 'fa-clock-rotate-left', 'route' => 'dashboard', 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'editor.templates', 'label' => 'قالب‌ها', 'icon' => 'fa-layer-group', 'planned' => true],
                ['key' => 'editor.drafts', 'label' => 'پیش‌نویس‌ها', 'icon' => 'fa-file-pen', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'own'],
                ['key' => 'editor.favorites', 'label' => 'موارد مورد علاقه', 'icon' => 'fa-star', 'planned' => true, 'permission' => 'documents.view', 'scope' => 'own'],
            ],
        ],
        [
            'key' => 'automation', 'label' => 'اتوماسیون و گردش کار', 'icon' => 'fa-diagram-project',
            'items' => [
                ['key' => 'automation.workflows', 'label' => 'گردش‌های کار', 'icon' => 'fa-route', 'planned' => true, 'permission' => 'workflows.view', 'scope' => 'team'],
                ['key' => 'automation.processes', 'label' => 'فرآیندها', 'icon' => 'fa-diagram-next', 'planned' => true, 'permission' => 'workflows.manage', 'scope' => 'organization'],
                ['key' => 'automation.rules', 'label' => 'قوانین', 'icon' => 'fa-filter-circle-dollar', 'planned' => true, 'permission' => 'workflows.manage', 'scope' => 'organization'],
                ['key' => 'automation.actions', 'label' => 'اقدامات خودکار', 'icon' => 'fa-bolt-lightning', 'planned' => true, 'permission' => 'workflows.execute', 'scope' => 'team'],
                ['key' => 'automation.runs', 'label' => 'اجرای‌های اخیر', 'icon' => 'fa-clock-rotate-left', 'planned' => true, 'permission' => 'workflows.view', 'scope' => 'team'],
                ['key' => 'automation.queue', 'label' => 'صف‌ها / اجرای‌ها', 'icon' => 'fa-bars-progress', 'planned' => true, 'permission' => 'workflows.view', 'scope' => 'organization'],
                ['key' => 'automation.errors', 'label' => 'خطاهای اجرای فرآیند', 'icon' => 'fa-triangle-exclamation', 'planned' => true, 'permission' => 'workflows.view', 'scope' => 'organization'],
            ],
        ],
        [
            'key' => 'ai', 'label' => 'هوش مصنوعی', 'icon' => 'fa-wand-magic-sparkles',
            'items' => [
                ['key' => 'ai.assistant', 'label' => 'دستیار هوشمند', 'icon' => 'fa-message-bot', 'route' => 'editor', 'permission' => 'ai.use', 'scope' => 'own'],
                ['key' => 'ai.tools', 'label' => 'ابزارهای AI', 'icon' => 'fa-sparkles', 'route' => 'editor', 'permission' => 'ai.use', 'scope' => 'own'],
                ['key' => 'ai.analytics', 'label' => 'تحلیل‌ها', 'icon' => 'fa-chart-line', 'planned' => true, 'permission' => 'ai.view', 'scope' => 'team'],
                ['key' => 'ai.suggestions', 'label' => 'پیشنهادها', 'icon' => 'fa-lightbulb', 'planned' => true, 'permission' => 'ai.use', 'scope' => 'own'],
                ['key' => 'ai.history', 'label' => 'تاریخچه عملیات AI', 'icon' => 'fa-clock-rotate-left', 'planned' => true, 'permission' => 'ai.view', 'scope' => 'own'],
                ['key' => 'ai.settings', 'label' => 'تنظیمات AI', 'icon' => 'fa-sliders', 'route' => 'admin.index', 'fragment' => '#ai-settings', 'admin_only' => true],
                ['key' => 'ai.quota', 'label' => 'مصرف و سهمیه AI', 'icon' => 'fa-gauge-high', 'planned' => true, 'permission' => 'ai.view', 'scope' => 'own'],
            ],
        ],
        [
            'key' => 'collaboration', 'label' => 'تیم و همکاری', 'icon' => 'fa-people-group',
            'items' => [
                ['key' => 'collaboration.members', 'label' => 'اعضای تیم', 'icon' => 'fa-users', 'planned' => true, 'permission' => 'team.view', 'scope' => 'team'],
                ['key' => 'collaboration.teams', 'label' => 'تیم‌ها', 'icon' => 'fa-users-rectangle', 'planned' => true, 'permission' => 'team.manage', 'scope' => 'organization'],
                ['key' => 'collaboration.invites', 'label' => 'دعوت‌ها', 'icon' => 'fa-user-plus', 'planned' => true, 'permission' => 'team.manage', 'scope' => 'organization'],
                ['key' => 'collaboration.shared', 'label' => 'اشتراک‌گذاری', 'icon' => 'fa-share-nodes', 'planned' => true, 'permission' => 'documents.share', 'scope' => 'team'],
                ['key' => 'collaboration.work', 'label' => 'همکاری‌ها', 'icon' => 'fa-handshake', 'planned' => true, 'permission' => 'team.view', 'scope' => 'team'],
                ['key' => 'collaboration.activity', 'label' => 'فعالیت تیم', 'icon' => 'fa-chart-simple', 'planned' => true, 'permission' => 'team.view', 'scope' => 'team'],
                ['key' => 'collaboration.requests', 'label' => 'درخواست‌ها', 'icon' => 'fa-inbox', 'planned' => true, 'permission' => 'team.view', 'scope' => 'team'],
            ],
        ],
        [
            'key' => 'reports', 'label' => 'گزارش‌ها و تحلیل‌ها', 'icon' => 'fa-chart-pie',
            'items' => [
                ['key' => 'reports.overview', 'label' => 'گزارش کلی', 'icon' => 'fa-chart-column', 'planned' => true, 'permission' => 'reports.view', 'scope' => 'organization'],
                ['key' => 'reports.users', 'label' => 'فعالیت کاربران', 'icon' => 'fa-user-chart', 'planned' => true, 'permission' => 'reports.users', 'scope' => 'organization'],
                ['key' => 'reports.team', 'label' => 'عملکرد تیم', 'icon' => 'fa-people-group', 'planned' => true, 'permission' => 'reports.team', 'scope' => 'team'],
                ['key' => 'reports.documents', 'label' => 'اسناد', 'icon' => 'fa-file-chart-column', 'planned' => true, 'permission' => 'reports.documents', 'scope' => 'organization'],
                ['key' => 'reports.workflows', 'label' => 'گردش کار', 'icon' => 'fa-route', 'planned' => true, 'permission' => 'reports.workflows', 'scope' => 'organization'],
                ['key' => 'reports.ai', 'label' => 'AI', 'icon' => 'fa-wand-magic-sparkles', 'planned' => true, 'permission' => 'reports.ai', 'scope' => 'organization'],
                ['key' => 'reports.resources', 'label' => 'مصرف منابع', 'icon' => 'fa-gauge', 'planned' => true, 'permission' => 'reports.resources', 'scope' => 'organization'],
                ['key' => 'reports.finance', 'label' => 'گزارش‌های مالی', 'icon' => 'fa-wallet', 'route' => 'admin.finance', 'permission' => 'finance.view', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'reports.system', 'label' => 'گزارش‌های سیستمی', 'icon' => 'fa-server', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'notifications', 'label' => 'اعلان‌ها و پیام‌ها', 'icon' => 'fa-bell',
            'items' => [
                ['key' => 'notifications.alerts', 'label' => 'اعلان‌ها', 'icon' => 'fa-bell', 'route' => 'announcements'],
                ['key' => 'notifications.messages', 'label' => 'پیام‌ها', 'icon' => 'fa-messages', 'planned' => true],
                ['key' => 'notifications.notices', 'label' => 'اطلاعیه‌ها', 'icon' => 'fa-bullhorn', 'route' => 'announcements'],
                ['key' => 'notifications.activity', 'label' => 'فعالیت‌ها', 'icon' => 'fa-list-check', 'planned' => true],
                ['key' => 'notifications.settings', 'label' => 'تنظیمات اعلان', 'icon' => 'fa-sliders', 'planned' => true],
            ],
        ],
        [
            'key' => 'access', 'label' => 'مدیریت کاربران و دسترسی‌ها', 'icon' => 'fa-user-shield', 'admin_only' => true,
            'items' => [
                ['key' => 'access.users', 'label' => 'کاربران', 'icon' => 'fa-users', 'route' => 'admin.index', 'fragment' => '#users', 'admin_only' => true],
                ['key' => 'access.roles', 'label' => 'نقش‌ها', 'icon' => 'fa-id-badge', 'planned' => true, 'permission' => 'access.manage', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'access.permissions', 'label' => 'مجوزها', 'icon' => 'fa-key', 'planned' => true, 'permission' => 'access.manage', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'access.groups', 'label' => 'گروه‌ها', 'icon' => 'fa-layer-group', 'planned' => true, 'permission' => 'access.manage', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'access.teams', 'label' => 'تیم‌ها', 'icon' => 'fa-users-rectangle', 'planned' => true, 'permission' => 'team.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'access.requests', 'label' => 'درخواست‌های دسترسی', 'icon' => 'fa-user-clock', 'planned' => true, 'permission' => 'access.manage', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'access.activity', 'label' => 'فعالیت کاربران', 'icon' => 'fa-list-check', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'access.sessions', 'label' => 'نشست‌ها', 'icon' => 'fa-display', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'access.status', 'label' => 'وضعیت حساب‌ها', 'icon' => 'fa-user-check', 'planned' => true, 'permission' => 'access.manage', 'scope' => 'global', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'organization', 'label' => 'مدیریت سازمان', 'icon' => 'fa-building', 'admin_only' => true,
            'items' => [
                ['key' => 'organization.info', 'label' => 'اطلاعات سازمان', 'icon' => 'fa-building', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.structure', 'label' => 'ساختار سازمانی', 'icon' => 'fa-sitemap', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.units', 'label' => 'واحدها', 'icon' => 'fa-diagram-project', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.teams', 'label' => 'تیم‌ها', 'icon' => 'fa-users-rectangle', 'planned' => true, 'permission' => 'team.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.members', 'label' => 'اعضا', 'icon' => 'fa-users', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.policies', 'label' => 'سیاست‌ها', 'icon' => 'fa-shield-halved', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.settings', 'label' => 'تنظیمات سازمان', 'icon' => 'fa-gear', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
                ['key' => 'organization.brand', 'label' => 'برند سازمان', 'icon' => 'fa-palette', 'planned' => true, 'permission' => 'organization.manage', 'scope' => 'organization', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'security', 'label' => 'امنیت و نظارت', 'icon' => 'fa-shield-halved', 'admin_only' => true,
            'items' => [
                ['key' => 'security.report', 'label' => 'گزارش امنیتی', 'icon' => 'fa-file-shield', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.sensitive', 'label' => 'فعالیت‌های حساس', 'icon' => 'fa-user-lock', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.logs', 'label' => 'لاگ‌ها', 'icon' => 'fa-list', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.sessions', 'label' => 'نشست‌ها', 'icon' => 'fa-display', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.logins', 'label' => 'ورودها', 'icon' => 'fa-right-to-bracket', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.events', 'label' => 'رویدادهای امنیتی', 'icon' => 'fa-triangle-exclamation', 'planned' => true, 'permission' => 'system.audit', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.access', 'label' => 'دسترسی‌های حساس', 'icon' => 'fa-key', 'planned' => true, 'permission' => 'access.manage', 'scope' => 'global', 'admin_only' => true],
                ['key' => 'security.status', 'label' => 'وضعیت سیستم', 'icon' => 'fa-server', 'route' => 'admin.index', 'fragment' => '#operations', 'admin_only' => true],
            ],
        ],
        [
            'key' => 'settings', 'label' => 'تنظیمات و پشتیبانی', 'icon' => 'fa-gear',
            'items' => [
                ['key' => 'settings.account', 'label' => 'تنظیمات حساب', 'icon' => 'fa-user-gear', 'planned' => true],
                ['key' => 'settings.general', 'label' => 'تنظیمات عمومی', 'icon' => 'fa-sliders', 'route' => 'admin.index', 'fragment' => '#settings', 'admin_only' => true],
                ['key' => 'settings.ui', 'label' => 'تنظیمات رابط کاربری', 'icon' => 'fa-display', 'planned' => true],
                ['key' => 'settings.notifications', 'label' => 'اعلان‌ها', 'icon' => 'fa-bell', 'planned' => true],
                ['key' => 'settings.security', 'label' => 'امنیت', 'icon' => 'fa-lock', 'planned' => true],
                ['key' => 'settings.finance', 'label' => 'مالی', 'icon' => 'fa-wallet', 'route' => 'admin.finance', 'admin_only' => true],
                ['key' => 'settings.email', 'label' => 'ایمیل', 'icon' => 'fa-envelope', 'route' => 'admin.emails', 'admin_only' => true],
                ['key' => 'settings.support', 'label' => 'پشتیبانی', 'icon' => 'fa-headset', 'route' => 'support', 'permission' => 'support.use', 'scope' => 'own'],
                ['key' => 'settings.help', 'label' => 'راهنما', 'icon' => 'fa-circle-question', 'planned' => true],
                ['key' => 'settings.about', 'label' => 'درباره سیستم', 'icon' => 'fa-circle-info', 'planned' => true],
            ],
        ],
    ],
];
