@extends('layouts.app')
@section('content')
<div class="farast-cart" dir="rtl"><div class="cart-card"><div class="cart-head"><h1>سبد خرید</h1><a href="{{ route('store') }}">ادامه خرید</a></div><div id="cartItems">@forelse($cart['items'] as $item)<div class="cart-row" data-product="{{ $item['product_id'] }}"><div><strong>{{ $item['title'] }}</strong><small>{{ number_format($item['unit_price_rials']/10) }} تومان برای هر عدد</small></div><div class="cart-controls"><button data-cart-action="minus" type="button">−</button><b>{{ $item['quantity'] }}</b><button data-cart-action="plus" type="button">+</button><button data-cart-action="remove" type="button">حذف</button></div><strong>{{ number_format($item['line_total_rials']/10) }} تومان</strong></div>@empty<div class="cart-empty">سبد خرید شما خالی است.</div>@endforelse</div>@if(!empty($cart['items']))<div class="cart-total"><span>مبلغ کالاها</span><strong id="cartTotal">{{ number_format($cart['total_rials']/10) }} تومان</strong></div><form method="post" action="{{ route('cart.checkout') }}" class="cart-checkout">@csrf<label><input type="checkbox" name="accept_terms" value="1" required> قوانین خرید دیجیتال را می‌پذیرم.</label><button type="submit">ادامه به پرداخت</button></form>@endif<p class="cart-note">مبلغ checkout دوباره در سرور محاسبه و قیمت فعلی محصولات با سفارش تطبیق داده می‌شود.</p></div></div>
@endsection
@push('styles')<style>.farast-cart{min-height:calc(100vh - 80px);background:#f5f8fc;padding:45px 15px}.cart-card{max-width:900px;margin:auto;background:#fff;border:1px solid #e0e7ef;border-radius:15px;padding:20px}.cart-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #edf1f5;padding-bottom:12px}.cart-head h1{font-size:1.1rem;margin:0}.cart-head a{font-size:.7rem;color:#1769ff;text-decoration:none}.cart-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:18px;align-items:center;padding:14px 0;border-bottom:1px solid #edf1f5;font-size:.72rem}.cart-row small{display:block;color:#7b899b;font-size:.61rem;margin-top:4px}.cart-controls{display:flex;align-items:center;gap:6px}.cart-controls button{height:28px;border:1px solid #dbe3ed;background:#fff;border-radius:6px;padding:0 8px;font:inherit;font-size:.63rem;cursor:pointer}.cart-controls button:hover{background:#edf4ff}.cart-empty{text-align:center;padding:55px;color:#7b899b;font-size:.72rem}.cart-total{display:flex;justify-content:space-between;margin-top:18px;font-size:.8rem}.cart-total strong{color:#1769ff}.cart-checkout{display:flex;align-items:center;gap:12px;margin-top:15px}.cart-checkout label{font-size:.65rem;color:#697b91}.cart-checkout button{margin-right:auto;border:0;border-radius:8px;background:#1769ff;color:#fff;padding:10px 18px;font:inherit;font-size:.7rem;font-weight:800;cursor:pointer}.cart-note{font-size:.62rem;color:#8492a3;line-height:1.8}@media(max-width:600px){.cart-row{grid-template-columns:1fr}.cart-controls{justify-content:flex-start}.cart-checkout{align-items:stretch;flex-direction:column}.cart-checkout button{width:100%}}
</style>@endpush
@push('scripts')
<script>
(()=>{const csrf=document.querySelector('meta[name="csrf-token"]')?.content||'';async function call(url,body){const r=await fetch(url,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify(body||{})});const j=await r.json();if(!r.ok)throw new Error(j.message||'خطا در سبد خرید');return j}document.querySelectorAll('.cart-row').forEach(row=>row.addEventListener('click',async e=>{const b=e.target.closest('[data-cart-action]');if(!b)return;const id=row.dataset.product;const action=b.dataset.cartAction;try{if(action==='remove')await call('/cart/products/'+id+'/remove');else{const current=Number(row.querySelector('.cart-controls b').textContent||1);const q=current+(action==='plus'?1:-1);await call('/cart/products/'+id+'/update',{quantity:Math.max(0,q)})}location.reload()}catch(err){alert(err.message)}}))})();
</script>@endpush
