@extends('layouts.app')
@section('content')
<div class="farast-store" dir="rtl">
  <section class="store-hero"><div><span class="store-kicker">فروشگاه دیجیتال فراست</span><h1>فایل آماده، پیش‌نمایش واقعی، خرید امن</h1><p>محصولات منتشرشده از backend نمایش داده می‌شوند؛ قیمت و وضعیت محصول از سرور خوانده می‌شود.</p></div><form method="get" action="{{ route('store') }}" class="store-search"><input name="q" value="{{ $q }}" placeholder="جستجوی فایل، عنوان یا موضوع…" aria-label="جستجوی فروشگاه"><button type="submit">جستجو</button></form></section>
  <div class="store-layout">
    <aside class="store-filters"><strong>دسته‌بندی‌ها</strong><a class="{{ !$category ? 'active' : '' }}" href="{{ route('store') }}">همه محصولات</a>@foreach($categories as $cat)<a class="{{ $category===$cat->slug ? 'active' : '' }}" href="{{ route('store.category',$cat->slug) }}">{{ $cat->name }}</a>@endforeach</aside>
    <main><div class="store-toolbar"><strong>{{ $q ? 'نتایج جستجو' : 'محصولات منتشرشده' }}</strong><span>{{ $products->total() }} محصول</span></div><div class="product-grid">@forelse($products as $product)<article class="product-card"><a class="product-cover" href="{{ route('store.product',$product->slug) }}">@if($product->cover_path)<img src="{{ asset($product->cover_path) }}" alt="{{ $product->title }}" loading="lazy">@else<span>FARAST</span>@endif</a><div class="product-card-body"><small>{{ $product->category?->name }}</small><h2><a href="{{ route('store.product',$product->slug) }}">{{ $product->title }}</a></h2><p>{{ \Illuminate\Support\Str::limit($product->short_description ?: $product->description, 110) }}</p><div class="product-price">{{ number_format((int)$product->price_rials / 10) }} تومان</div></div></article>@empty<div class="store-empty"><strong>محصولی پیدا نشد.</strong><span>دسته‌بندی یا عبارت جستجو را تغییر دهید.</span></div>@endforelse</div>{{ $products->links() }}</main>
  </div>
</div>
@endsection
@push('styles')
<style>
.farast-store{min-height:calc(100vh - 80px);background:#f5f8fc;color:#20334d;padding-bottom:60px}.store-hero{padding:54px clamp(18px,6vw,90px);display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,480px);gap:30px;align-items:end;background:linear-gradient(135deg,#091735,#173e79);color:#fff}.store-kicker{font-size:.75rem;color:#8edff6}.store-hero h1{font-size:clamp(1.7rem,3vw,2.8rem);margin:8px 0}.store-hero p{margin:0;color:#d3e0f3;font-size:.82rem}.store-search{display:flex;background:#fff;border-radius:12px;padding:5px}.store-search input{min-width:0;flex:1;border:0;outline:0;padding:0 10px;font:inherit}.store-search button{border:0;border-radius:8px;background:#1769ff;color:#fff;padding:9px 16px;font:inherit;cursor:pointer}.store-layout{max-width:1320px;margin:28px auto;padding:0 18px;display:grid;grid-template-columns:210px minmax(0,1fr);gap:22px}.store-filters{background:#fff;border:1px solid #e1e8f0;border-radius:13px;padding:12px;height:max-content;position:sticky;top:15px}.store-filters strong{display:block;margin:3px 8px 8px;font-size:.75rem}.store-filters a{display:block;padding:9px;border-radius:7px;color:#63758b;text-decoration:none;font-size:.7rem}.store-filters a:hover,.store-filters a.active{background:#edf4ff;color:#145fbd;font-weight:700}.store-toolbar{display:flex;justify-content:space-between;align-items:center;margin:0 0 12px;font-size:.72rem}.store-toolbar span{color:#8290a3}.product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.product-card{background:#fff;border:1px solid #e0e7ef;border-radius:13px;overflow:hidden;box-shadow:0 3px 12px rgba(24,45,73,.05)}.product-cover{height:190px;background:linear-gradient(135deg,#0d2147,#2b68c8);display:grid;place-items:center;text-decoration:none;color:#fff;font-weight:800}.product-cover img{width:100%;height:100%;object-fit:cover}.product-card-body{padding:13px}.product-card-body small{color:#73849a;font-size:.6rem}.product-card h2{font-size:.83rem;margin:5px 0}.product-card h2 a{color:#203c60;text-decoration:none}.product-card p{font-size:.65rem;color:#728198;line-height:1.7;min-height:38px;margin:0}.product-price{font-weight:800;color:#1769ff;font-size:.75rem;margin-top:10px}.store-empty{grid-column:1/-1;padding:60px;text-align:center;background:#fff;border:1px dashed #cfd9e5;border-radius:12px;display:grid;gap:8px}.store-empty span{font-size:.7rem;color:#78879b}@media(max-width:850px){.store-hero{grid-template-columns:1fr}.store-layout{grid-template-columns:1fr}.store-filters{position:static;display:flex;gap:5px;overflow:auto}.store-filters strong{display:none}.store-filters a{white-space:nowrap}.product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.store-hero{padding:35px 15px}.store-layout{padding:0 10px}.product-grid{grid-template-columns:1fr}.product-cover{height:170px}}
</style>
@endpush
