<?php
namespace App\Http\Controllers;
use App\Models\User;use App\Models\OtpChallenge;use Illuminate\Http\Request;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;
class AuthController extends Controller {
 public function showLogin(){return view('auth.login');}
 public function adminLogin(Request $r){$data=$r->validate(['mobile'=>'required','password'=>'required']);abort_unless(hash_equals((string)config('app.admin_mobile',env('ADMIN_MOBILE')),(string)$data['mobile']),403);$admin=User::where('mobile',$data['mobile'])->where('role','admin')->first();abort_unless($admin,403);abort_unless(Hash::check($data['password'],$admin->password),403);auth()->login($admin,true);$r->session()->regenerate();return redirect('/admin');}
 public function requestOtp(Request $r){$data=$r->validate(['mobile'=>['required','regex:/^09\d{9}$/']]);$mobile=$data['mobile'];$code=(string)random_int(100000,999999);OtpChallenge::where('mobile',$mobile)->whereNull('consumed_at')->update(['consumed_at'=>now()]);OtpChallenge::create(['mobile'=>$mobile,'code_hash'=>Hash::make($code),'expires_at'=>now()->addMinutes(3)]);session(['otp_mobile'=>$mobile]);return response()->json(['ok'=>true,'message'=>'کد تأیید ارسال شد','dev'=>app()->environment('local')?$code:null]);}
 public function verifyOtp(Request $r){$data=$r->validate(['code'=>'required|digits:6']);$mobile=session('otp_mobile');abort_unless($mobile,422);$otp=OtpChallenge::where('mobile',$mobile)->whereNull('consumed_at')->where('expires_at','>',now())->latest()->first();abort_unless($otp,422,'کد منقضی شده است');if($otp->attempts>=5)abort(429);$otp->increment('attempts');abort_unless(Hash::check($data['code'],$otp->code_hash),422,'کد نادرست است');$otp->update(['consumed_at'=>now()]);$user=User::firstOrCreate(['mobile'=>$mobile],['name'=>'کاربر '.substr($mobile,-4),'password'=>Str::random(32),'role'=>'user','is_verified'=>true]);$user->update(['is_verified'=>true]);auth()->login($user,true);$r->session()->regenerate();return redirect()->intended('/dashboard');}
 public function logout(Request $r){auth()->logout();$r->session()->invalidate();$r->session()->regenerateToken();return redirect('/');}
}
