<?php
namespace App\Http\Controllers;
use App\Models\TypingDocument;use App\Models\EditorSession;use App\Services\PricingService;use App\Services\GeminiService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;
class EditorController extends Controller {
 public function pricing(){return view('pricing');}
 public function dashboard(){return view('dashboard',['documents'=>auth()->user()->documents()->latest()->get()]);}
 public function create(){return view('editor');}
 public function upload(Request $r){$f=$r->file('source');$r->validate(['source'=>'required|file|max:51200|mimes:jpg,jpeg,png,webp,pdf,zip']);$mime=$f->getMimeType();$path=$f->store('typing/'.auth()->id(),'private');return response()->json(['path'=>$path,'mime'=>$mime,'name'=>$f->getClientOriginalName()]);}
 public function analyze(Request $r,GeminiService $ai,PricingService $pricing){$data=$r->validate(['path'=>'required|string','mime'=>'required|string','text'=>'nullable|string|max:1000000']);$path=$data['path'];abort_unless(Str::startsWith($path,'typing/'.auth()->id().'/'),403);$bytes=Storage::disk('private')->get($path);$result=$ai->transcribe($data['mime'],base64_encode($bytes));if(($result['rejected']??false))return response()->json(['ok'=>false,'message'=>'این فایل شامل جدول، نمودار، شکل یا محتوای خارج از محدوده تایپ ساده است.'],422);$text=$result['text']??'';$pages=max(1,(int)($result['page_count']??1));$quote=$pricing->quote($text,$pages);$doc=TypingDocument::create(['user_id'=>auth()->id(),'title'=>'سند جدید','content'=>$text,'source_path'=>$path,'source_hash'=>hash('sha256',$bytes),'page_count'=>$pages,'word_count'=>$quote['word_count'],'language_mix'=>['fa'=>true,'en'=>preg_match('/[A-Za-z]/',$text)>0,'ar'=>false],'status'=>'analyzed','price_rials'=>$quote['price_rials'],'expires_at'=>now()->addDays((int)env('FILES_TTL_DAYS',14))]);return response()->json(['ok'=>true,'document_id'=>$doc->id,'text'=>$text,'pages'=>$pages,'price'=>$quote['price_rials'],'issues'=>$result['issues']??[],'breakdown'=>$quote['breakdown']]);}
 public function save(Request $r){$d=$r->validate(['document_id'=>'required|integer','content'=>'required|string|max:2000000']);$doc=TypingDocument::where('id',$d['document_id'])->where('user_id',auth()->id())->firstOrFail();$doc->update(['content'=>$d['content'],'word_count'=>count(preg_split('/\s+/u',trim($d['content']),-1,PREG_SPLIT_NO_EMPTY))]);return response()->json(['ok'=>true]);}
 public function heartbeat(Request $r){$token=$r->session()->get('editor_session_token');$s=EditorSession::where('token',$token)->where('user_id',auth()->id())->first();if($s){$s->update(['last_seen_at'=>now(),'expires_at'=>now()->addMinutes(20)]);}return response()->json(['ok'=>true]);}
}
