<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#0b1734"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="mobile-web-app-title" content="فراست">
<title>{{ $title ?? 'فراست' }}</title>
@php
$isEditor=request()->is('editor'); $isAdmin=request()->is('admin*'); $isDashboard=request()->routeIs('dashboard')||request()->routeIs('admin.*'); $isAuthPage=request()->is('login*')||request()->is('register')||request()->is('forgot-password*');
$headerAnnouncements=collect(); $footerSocial=[]; $farastCapabilities=null;
if($isEditor&&auth()->check()){$farastCapabilities=app(\App\Services\CapabilityService::class)->forUser(auth()->user());}
if(!$isEditor&&!$isAdmin&&!$isDashboard){if(\Illuminate\Support\Facades\Schema::hasTable('announcements')){$headerAnnouncements=\App\Models\Announcement::visible()->latest()->limit(5)->get();}if(\Illuminate\Support\Facades\Schema::hasTable('site_settings')){$footerRaw=\App\Models\SiteSetting::read('social_links','[]');$decodedSocial=json_decode((string)$footerRaw,true);if(is_array($decodedSocial)){$footerSocial=array_values(array_filter($decodedSocial,static fn($item)=>is_array($item)&&filter_var($item['url']??'',FILTER_VALIDATE_URL)));}}}
@endphp
<link rel="preconnect" href="https://cdnjs.cloudflare.com"><link rel="preconnect" href="https://cdn.jsdelivr.net"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
<link rel="stylesheet" href="/css/farast.css"><link rel="stylesheet" href="/css/ui-polish.css"><link rel="stylesheet" href="/css/site-premium.css"><link rel="stylesheet" href="/css/farast-app.css"><link rel="stylesheet" href="/css/finance.css">
@if($isDashboard)<link rel="stylesheet" href="/css/dashboard-navigation.css">@endif
@if($isEditor)
<meta name="farast-capabilities" content='@json($farastCapabilities)'><link rel="stylesheet" href="/css/voice.css"><link rel="stylesheet" href="/css/word-editor.css"><link rel="stylesheet" href="/css/word-editor-overrides.css"><link rel="stylesheet" href="/css/editor-pro.css"><link rel="stylesheet" href="/css/editor-workspace.css"><link rel="stylesheet" href="/css/editor-final-polish.css?v=20260914"><link rel="stylesheet" href="/css/editor-word-2026-chrome.css?v=20260914"><link rel="stylesheet" href="/css/editor-word-precision.css?v=20260914"><link rel="stylesheet" href="/css/editor-ai-ux.css?v=20260914"><link rel="stylesheet" href="/css/editor-file-picker.css?v=20260914"><link rel="stylesheet" href="/css/editor-scroll-final.css?v=20260914"><link rel="stylesheet" href="/css/editor-ai-selection-actions.css?v=20260915"><link rel="stylesheet" href="/css/editor-word-2026-responsive.css?v=20260916">
@endif
@if($isAdmin)<link rel="stylesheet" href="/css/admin.css">@endif
@if($isAuthPage)<link rel="stylesheet" href="/css/auth.css">@endif
</head>
<body class="{{ $isEditor?'editor-page-body':'' }} {{ $isAuthPage?'auth-page':'' }}">
@if(!$isEditor&&!$isAdmin&&!$isDashboard)
<header class="top premium-header" data-app-header><div class="header-inner"><a class="brand premium-brand" href="/" aria-label="فراست"><span class="brand-mark farast-symbol" aria-hidden="true"><i></i><i></i><i></i><i></i><b></b></span><span><b>FARAST</b><small>فراست | فروش فایل و خدمات هوشمند</small></span></a><div class="header-search" role="search"><i class="fa-solid fa-magnifying-glass"></i><input id="farastGlobalSearch" type="search" placeholder="جستجوی فایل، خدمت یا موضوع..." autocomplete="off"><button type="button" id="farastVoiceSearch" aria-label="جستجوی صوتی"><i class="fa-solid fa-microphone"></i></button></div><nav class="main-nav"><a href="/"><i class="fa-solid fa-house"></i><span>خانه</span></a><a href="/#farastStore"><i class="fa-solid fa-store"></i><span>فروشگاه</span></a><a href="/editor"><i class="fa-solid fa-pen-ruler"></i><span>تایپ و خدمات</span></a><a href="/pricing"><i class="fa-solid fa-tags"></i><span>قیمت</span></a>@auth<a href="/dashboard"><i class="fa-solid fa-table-cells-large"></i><span>فضای من</span></a><a href="/support"><i class="fa-solid fa-headset"></i><span>پشتیبانی</span></a>@if(auth()->user()->isAdmin())<a href="/admin"><i class="fa-solid fa-user-shield"></i><span>مدیریت</span></a>@endif @else<a href="/login"><i class="fa-solid fa-right-to-bracket"></i><span>ورود</span></a>@endauth</nav><div class="header-actions"><button type="button" class="header-icon-button" id="farastCartButton" aria-label="سبد خرید"><i class="fa-solid fa-bag-shopping"></i><b id="farastCartCount">0</b></button><a class="header-cta" href="/editor"><i class="fa-solid fa-bolt"></i><span>شروع کار</span></a></div></div></header>
@if($headerAnnouncements->isNotEmpty()&&request()->routeIs('home'))<div class="announcement-ticker"><div><i class="fa-solid fa-bullhorn"></i><b>{{ $headerAnnouncements->first()->title }}</b><span>{{ \Illuminate\Support\Str::limit($headerAnnouncements->first()->body,120) }}</span></div><a href="/announcements">مشاهده همه</a></div>@endif
@endif
<main id="app-main" class="{{ $isDashboard ? 'dashboard-shell' : '' }}">
@if($isDashboard && auth()->check())<div class="dashboard-shell-inner">@include('components.dashboard-navigation')@endif
@yield('content')
@if($isDashboard && auth()->check())</div>@endif
</main>
@if(!$isEditor&&!$isAdmin&&!$isDashboard)<aside class="farast-cart-drawer" id="farastCartDrawer" aria-hidden="true"><div class="farast-cart-head"><strong>سبد خرید</strong><button type="button" data-cart-close aria-label="بستن"><i class="fa-solid fa-xmark"></i></button></div><div class="farast-cart-body" id="farastCartBody"></div><div class="farast-cart-foot"><span>جمع</span><strong id="farastCartTotal">۰ تومان</strong><button type="button" id="farastCartCheckout" disabled>ادامه پرداخت</button></div></aside><div class="farast-cart-backdrop" id="farastCartBackdrop" hidden></div><div class="farast-connectivity" id="farastConnectivity" aria-live="polite" hidden><div class="farast-connectivity-card"><div class="farast-connectivity-copy"><strong id="farastConnectivityTitle">اتصال اینترنت در دسترس نیست</strong><span id="farastConnectivityMessage">بخش‌های ذخیره‌شده در دسترس می‌مانند.</span></div><button type="button" id="farastConnectivityRetry" aria-label="تلاش دوباره"><i class="fa-solid fa-rotate-right"></i></button></div></div><button type="button" id="farastSoundToggle" class="farast-sound-toggle" aria-label="فعال یا غیرفعال کردن صدای رابط" aria-pressed="false"><i class="fa-solid fa-volume-high"></i></button>@endif
@if(!$isEditor&&!$isAdmin&&!$isDashboard)<footer class="site-footer" dir="rtl"><div class="footer-top"><div class="footer-about"><div class="footer-brand"><span class="brand-mark farast-symbol"><i></i><i></i><i></i><i></i><b></b></span><b>فراست</b></div><p>فراست یک فضای یکپارچه برای فروش فایل‌های دیجیتال و ارائه خدمات تایپ، تبدیل، ویرایش و پردازش هوشمند است.</p></div><div class="footer-column"><h3>محصول و خدمات</h3><a href="/#farastStore">فروش فایل</a><a href="/editor">تایپ و تبدیل</a><a href="/pricing">قیمت‌گذاری</a><a href="/support">پشتیبانی</a></div><div class="footer-column"><h3>فضای کاربر</h3><a href="/dashboard">داشبورد</a><a href="/wallet">کیف پول</a><a href="/announcements">اعلانات</a></div></div><div class="footer-bottom"><span>© {{ now()->year }} فراست — تمامی حقوق محفوظ است.</span><div><a href="/privacy">حریم خصوصی</a><a href="/terms">قوانین استفاده</a><a href="/refund-policy">شرایط بازگشت وجه</a></div></footer>@endif
<script src="/js/farast-tab-lock.js"></script><script src="/js/farast.js"></script><script src="/js/farast-sound.js"></script>@if(!$isAdmin&&!$isDashboard)<script src="/js/farast-app.js"></script>@endif
@if($isEditor)<script src="/js/editor-polish.js?v=20260914"></script><script src="/js/editor-payment.js?v=20260914"></script><script src="/js/editor-redesign.js?v=20260914"></script><script src="/js/editor-redesign-guard.js?v=20260914"></script><script src="/js/editor-tools-patch.js?v=20260914"></script><script src="/js/editor-final-polish.js?v=20260914"></script><script src="/js/editor-functional-polish.js?v=20260914"></script><script src="/js/editor-word-2026-chrome.js?v=20260914"></script><script src="/js/editor-ai-ux.js?v=20260914"></script><script src="/js/editor-ai-selection-actions.js?v=20260915"></script><script src="/js/editor-voice-popover.js?v=20260916-3"></script><script src="/js/farast-voice.js?v=20260916-4"></script><script src="/js/editor-file-picker.js?v=20260914"></script>@endif
@stack('scripts')<script>document.documentElement.classList.add('js-ready');</script>
</body></html>